# Generated by Django 5.0.1 on 2024-05-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_joinrequest_admin_approved_alter_joinrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_url',
        ),
    ]
